//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;
namespace HotWheels.Map.MapReader
{
    public class MapObject
    {
        public MapObject(int id, GameObject obj, string name)
        {
            Id = id;
            Obj = obj;
            Name = name;
        }



        public int Id;
        public GameObject Obj;
        public string Name;
    }
}

