//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class MainMenuResX
{

	public static String ButtonPlay = "Graj";
	public static String ButtonMapEditor= "Edytor tras";
	public static String ButtonSettings= "Ustawienia";
	public static String ButtonsAbout= "Autorzy";
	public static String ButtonsExit= "Wyjdź";
	public static String LabelAbout= "Kamil Markuszewski";
	public static String ButtonLoadMap= "Wczytaj trase";
	public static String ButtonNewMap= "Nowa trasa";

	public static String ButtonDevelopement= "Development play";
	public static String ButtonSinglePlayer= "Jeden gracz";
	public static String MenuTitleMapEditor= "Edytor tras";
	public static String MenuTitleMain= "MENU";
	public static String MenuTitleSettings= "Ustawienia";
	public static String MenuTitleAbout= "Autorzy";


}


